### ISSUE TITLE
タイプウェル憲法も遊びたい

### ISSUE THREAD

**Issue by funatsufumiya** [fiore57/TypeWell-in-browser#7]
素晴らしいブラウザアプリをありがとうございます。タイプウェル憲法もプレイしてみたいのですが、文章を変えたりして簡単に対応できたりするものでしょうか。

**Comment by fiore57** [comment]
プレイしていただきありがとうございます。

タイプウェル憲法は、簡単な結果を表示するだけのものであれば、この「ブラウザ版タイプウェル国語R」のコードを一部使い回して実装することはそこまで難しくないと思われます。

しかし、憲法の文章があまりにも長く、文章データの用意やテストプレイがかなり面倒であること、および私自身が最近タイピングから離れており、新しいブラウザ版タイプウェルを作るモチベーションがないことから、私が作ることは恐らくありません。国語R以外のブラウザ版タイプウェルを作るとしても、比較的作業量の少ないタイプウェル英単語・オリジナル・国語Kの方を優先すると思うので、憲法は相当厳しいです。

**Comment by funatsufumiya** [comment]
ありがとうございます。フォークしていろいろ試してみます。
